#!/bin/bash

SERVICE="ffmpeg"

if [ -z "$1" ]; then
  echo "Starting Cameras"
elif [ $1 == restart ]; then
  echo "Kill old ffmpeg jobs"
  /usr/bin/pkill $SERVICE
  sleep 3
fi

#cam1 (wyze)
RTSP_URL1="rtsp://officecam:camtest1@192.168.1.137/live"
DEST_URL1="rtmp://192.168.1.128:1935/cam1/rtsp"
STARTCAM1="ffmpeg -use_wallclock_as_timestamps 1 -i ${RTSP_URL1} -c copy -f flv ${DEST_URL1}"

#cam2 (reolink)
RTSP_URL2="rtmp://192.168.1.138:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=camtest1"
DEST_URL2="rtmp://192.168.1.128:1935/cam2/rtsp"
STARTCAM2="ffmpeg -use_wallclock_as_timestamps 1 -i ${RTSP_URL2} -c copy -f flv ${DEST_URL2}"

#cam3
#RTSP_URL3="rtsp://nico:fluffykins@192.168.10.40/live"
#DEST_URL3="rtmp://192.168.1.16:1935/cam3/rtsp"
#STARTCAM3="ffmpeg -use_wallclock_as_timestamps 1 -i ${RTSP_URL3} -c copy -f flv ${DEST_URL3}"

#cam4
#RTSP_URL4="rtmp://192.168.1.128:1935/bcs/channel0_ext.bcs?channel=0&stream=0&user=admin&password=camtest1"
#DEST_URL4="rtmp://192.168.1.128/cam4/rtsp"
#STARTCAM4="ffmpeg -use_wallclock_as_timestamps 1 -i ${RTSP_URL4} -c copy -f flv ${DEST_URL4}"

if /usr/bin/pgrep $SERVICE > /dev/null
then
	echo "${SERVICE} is already running."
else
	echo "${SERVICE} is NOT running! Starting now..."
	$STARTCAM1 &
	$STARTCAM2 
#	$STARTCAM3 &
#	$STARTCAM4
fi
